// generated by Fast Light User Interface Designer (fluid) version 1.0100

#ifndef flminicalc_h
#define flminicalc_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <stdio.h>

class CalcUI {
  enum { NONE, ADD, SUB, MUL, DIV, EQUALS };
  int point; int state; int act; double val; double lval; double mval;
public:
  CalcUI();
private:
  Fl_Window *MainWindow;
  Fl_Group *NumberGr;
  Fl_Input *NumberInput;
  inline void cb_NumberInput_i(Fl_Input*, void*);
  static void cb_NumberInput(Fl_Input*, void*);
  Fl_Group *ButtonGr;
  inline void cb_0_i(Fl_Button*, void*);
  static void cb_0(Fl_Button*, void*);
  inline void cb_1_i(Fl_Button*, void*);
  static void cb_1(Fl_Button*, void*);
  inline void cb_2_i(Fl_Button*, void*);
  static void cb_2(Fl_Button*, void*);
  inline void cb_3_i(Fl_Button*, void*);
  static void cb_3(Fl_Button*, void*);
  inline void cb_4_i(Fl_Button*, void*);
  static void cb_4(Fl_Button*, void*);
  inline void cb_5_i(Fl_Button*, void*);
  static void cb_5(Fl_Button*, void*);
  inline void cb_6_i(Fl_Button*, void*);
  static void cb_6(Fl_Button*, void*);
  inline void cb_7_i(Fl_Button*, void*);
  static void cb_7(Fl_Button*, void*);
  inline void cb_8_i(Fl_Button*, void*);
  static void cb_8(Fl_Button*, void*);
  inline void cb_9_i(Fl_Button*, void*);
  static void cb_9(Fl_Button*, void*);
  inline void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
  inline void cb_a_i(Fl_Button*, void*);
  static void cb_a(Fl_Button*, void*);
  inline void cb_b_i(Fl_Button*, void*);
  static void cb_b(Fl_Button*, void*);
  inline void cb_c_i(Fl_Button*, void*);
  static void cb_c(Fl_Button*, void*);
  inline void cb_d_i(Fl_Button*, void*);
  static void cb_d(Fl_Button*, void*);
  inline void cb_M_i(Fl_Button*, void*);
  static void cb_M(Fl_Button*, void*);
  inline void cb_e_i(Fl_Button*, void*);
  static void cb_e(Fl_Button*, void*);
  inline void cb_C_i(Fl_Button*, void*);
  static void cb_C(Fl_Button*, void*);
  inline void cb_f_i(Fl_Button*, void*);
  static void cb_f(Fl_Button*, void*);
  inline void cb_Q_i(Fl_Button*, void*);
  static void cb_Q(Fl_Button*, void*);
public:
  void show(int argc, char **argv);
private:
  void set_val(double newval);
public:
  void update_win();
private:
  void handle_action(int action);
  void handle_number(int num);
  void reset_vals();
  void handle_error();
};
#endif
