// generated by Fast Light User Interface Designer (fluid) version 1.0100

#include "flminicalc.h"
#include "main.h"

inline void CalcUI::cb_NumberInput_i(Fl_Input*, void*) {
  set_val(strtod(NumberInput->value(), NULL));
update_win();
}
void CalcUI::cb_NumberInput(Fl_Input* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_NumberInput_i(o,v);
}

inline void CalcUI::cb_0_i(Fl_Button*, void*) {
  handle_number(0);
update_win();
}
void CalcUI::cb_0(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_0_i(o,v);
}

inline void CalcUI::cb_1_i(Fl_Button*, void*) {
  handle_number(1);
update_win();
}
void CalcUI::cb_1(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_1_i(o,v);
}

inline void CalcUI::cb_2_i(Fl_Button*, void*) {
  handle_number(2);
update_win();
}
void CalcUI::cb_2(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_2_i(o,v);
}

inline void CalcUI::cb_3_i(Fl_Button*, void*) {
  handle_number(3);
update_win();
}
void CalcUI::cb_3(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_3_i(o,v);
}

inline void CalcUI::cb_4_i(Fl_Button*, void*) {
  handle_number(4);
update_win();
}
void CalcUI::cb_4(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_4_i(o,v);
}

inline void CalcUI::cb_5_i(Fl_Button*, void*) {
  handle_number(5);
update_win();
}
void CalcUI::cb_5(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_5_i(o,v);
}

inline void CalcUI::cb_6_i(Fl_Button*, void*) {
  handle_number(6);
update_win();
}
void CalcUI::cb_6(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_6_i(o,v);
}

inline void CalcUI::cb_7_i(Fl_Button*, void*) {
  handle_number(7);
update_win();
}
void CalcUI::cb_7(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_7_i(o,v);
}

inline void CalcUI::cb_8_i(Fl_Button*, void*) {
  handle_number(8);
update_win();
}
void CalcUI::cb_8(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_8_i(o,v);
}

inline void CalcUI::cb_9_i(Fl_Button*, void*) {
  handle_number(9);
update_win();
}
void CalcUI::cb_9(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_9_i(o,v);
}

inline void CalcUI::cb__i(Fl_Button*, void*) {
  handle_action(EQUALS);
update_win();
}
void CalcUI::cb_(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb__i(o,v);
}

inline void CalcUI::cb_a_i(Fl_Button*, void*) {
  handle_action(ADD);
update_win();
}
void CalcUI::cb_a(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_a_i(o,v);
}

inline void CalcUI::cb_b_i(Fl_Button*, void*) {
  handle_action(SUB);
update_win();
}
void CalcUI::cb_b(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_b_i(o,v);
}

inline void CalcUI::cb_c_i(Fl_Button*, void*) {
  handle_action(MUL);
update_win();
}
void CalcUI::cb_c(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_c_i(o,v);
}

inline void CalcUI::cb_d_i(Fl_Button*, void*) {
  handle_action(DIV);
update_win();
}
void CalcUI::cb_d(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_d_i(o,v);
}

inline void CalcUI::cb_M_i(Fl_Button*, void*) {
  float tval = val;
if(mval != 0)
	set_val(mval);
mval = tval;
update_win();
}
void CalcUI::cb_M(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_M_i(o,v);
}

inline void CalcUI::cb_e_i(Fl_Button*, void*) {
  point = (point ? point : 1);
}
void CalcUI::cb_e(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_e_i(o,v);
}

inline void CalcUI::cb_C_i(Fl_Button*, void*) {
  set_val(0);
point = 0;
state = 0;
update_win();
}
void CalcUI::cb_C(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_C_i(o,v);
}

inline void CalcUI::cb_f_i(Fl_Button*, void*) {
  set_val(-val);
update_win();
}
void CalcUI::cb_f(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_f_i(o,v);
}

inline void CalcUI::cb_Q_i(Fl_Button*, void*) {
  MainWindow->hide();
}
void CalcUI::cb_Q(Fl_Button* o, void* v) {
  ((CalcUI*)(o->parent()->parent()->parent()->user_data()))->cb_Q_i(o,v);
}

CalcUI::CalcUI() {
  Fl_Window* w;
  reset_vals();
  { Fl_Window* o = MainWindow = new Fl_Window(185, 220);
    w = o;
    o->color(56);
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 0, 185, 220);
      { Fl_Group* o = NumberGr = new Fl_Group(0, 0, 185, 50);
        { Fl_Input* o = NumberInput = new Fl_Input(5, 5, 175, 45);
          o->type(1);
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color(50);
          o->selection_color(26);
          o->labeltype(FL_NO_LABEL);
          o->labelcolor(79);
          o->textfont(14);
          o->textsize(26);
          o->callback((Fl_Callback*)cb_NumberInput);
          o->align(FL_ALIGN_RIGHT);
        }
        o->end();
      }
      { Fl_Group* o = ButtonGr = new Fl_Group(0, 45, 185, 175);
        { Fl_Button* o = new Fl_Button(40, 175, 35, 40, "0");
          o->color(253);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_0);
        }
        { Fl_Button* o = new Fl_Button(5, 135, 35, 40, "1");
          o->color(245);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_1);
        }
        { Fl_Button* o = new Fl_Button(40, 135, 35, 40, "2");
          o->color(245);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_2);
        }
        { Fl_Button* o = new Fl_Button(75, 135, 35, 40, "3");
          o->color(245);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_3);
        }
        { Fl_Button* o = new Fl_Button(5, 95, 35, 40, "4");
          o->color(237);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_4);
        }
        { Fl_Button* o = new Fl_Button(40, 95, 35, 40, "5");
          o->color(237);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_5);
        }
        { Fl_Button* o = new Fl_Button(75, 95, 35, 40, "6");
          o->color(237);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_6);
        }
        { Fl_Button* o = new Fl_Button(5, 55, 35, 40, "7");
          o->color(229);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_7);
        }
        { Fl_Button* o = new Fl_Button(40, 55, 35, 40, "8");
          o->color(229);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_8);
        }
        { Fl_Button* o = new Fl_Button(75, 55, 35, 40, "9");
          o->color(229);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_9);
        }
        { Fl_Button* o = new Fl_Button(145, 175, 35, 40, "=");
          o->color(1);
          o->labelfont(1);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_);
        }
        { Fl_Button* o = new Fl_Button(110, 55, 35, 40, "+");
          o->color(141);
          o->labelsize(20);
          o->callback((Fl_Callback*)cb_a);
        }
        { Fl_Button* o = new Fl_Button(110, 95, 35, 40, "-");
          o->color(149);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_b);
        }
        { Fl_Button* o = new Fl_Button(110, 135, 35, 40, "*");
          o->color(157);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_c);
        }
        { Fl_Button* o = new Fl_Button(110, 175, 35, 40, "/");
          o->color(165);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_d);
        }
        { Fl_Button* o = new Fl_Button(5, 175, 35, 40, "M");
          o->color(119);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_M);
        }
        { Fl_Button* o = new Fl_Button(75, 175, 35, 40, ".");
          o->color(223);
          o->labelsize(24);
          o->callback((Fl_Callback*)cb_e);
        }
        { Fl_Button* o = new Fl_Button(145, 135, 35, 40, "C");
          o->color(54);
          o->labelsize(23);
          o->callback((Fl_Callback*)cb_C);
        }
        { Fl_Button* o = new Fl_Button(145, 95, 35, 40, "+/-");
          o->color(93);
          o->labelsize(20);
          o->callback((Fl_Callback*)cb_f);
        }
        { Fl_Button* o = new Fl_Button(145, 55, 35, 40, "Q");
          o->color(0);
          o->labelsize(23);
          o->labelcolor(63);
          o->callback((Fl_Callback*)cb_Q);
        }
        o->end();
      }
      o->end();
    }
    o->end();
  }
}

void CalcUI::show(int argc, char **argv) {
  MainWindow->show(argc, argv);
}

void CalcUI::set_val(double newval) {
  val=newval;
}

void CalcUI::update_win() {
  char *str;
str = fl2str(val);
if(str == NULL) {
	handle_error();
} else {
	NumberInput->value(str);
	NumberInput->redraw();
}
}

void CalcUI::handle_action(int action) {
  switch(action) {
	case ADD:
	case SUB:
	case MUL:
	case DIV:
		state = 1;
		act = action;
		lval = val;
		break;
	case EQUALS:
		state = 1;
		switch(act) {
			case ADD:
				val = lval+val;
				break;
			case SUB:
				val = lval-val;
				break;
			case MUL:
				val = lval*val;
				break;
			case DIV:
				if(val != 0) {
					val = lval/val;
				}
				break;
		}
		break;
}
}

void CalcUI::handle_number(int num) {
  if(state == 1) {
	val = num;
	state = 0;
	point = 0;
} else if(point == 0) {
	val = (val*10)+num;
} else {
	val += ((double)num / pow(10,point));
	point++;
}
}

void CalcUI::reset_vals() {
  point= 0;
state = 0;
act = NONE;
val  = 0.0;
lval = 0.0;
mval = 0.0;
}

void CalcUI::handle_error() {
  NumberInput->value("   Error  ");
NumberInput->redraw();
reset_vals();
}
